version: '3'
services:

  postgres:
    image: postgres:13
    container_name: postgres-certification
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - certification-network
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak-certification
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_SPI_COOKIE_SECURE_COOKIE_SAME_SITE: None
      KC_SPI_COOKIE_DEFAULT_COOKIE_SAME_SITE: None
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - certification-network

networks:
  certification-network:
    driver: bridge
