spring:
  application:
    name: agence-bancaire-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/certification-realm
          jwk-set-uri: http://localhost:8080/realms/certification-realm/protocol/openid-connect/certs

  datasource:
    url: jdbc:h2:mem:banquedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8083

springdoc:
  api-docs:
    path: /swagger-ui/index.html
  swagger-ui:
    path: /swagger-ui.html