test: hihi
spring:
  application:
    name: COMMERCANT-SERVICE-SERVER

  datasource:
    url: jdbc:h2:mem:commercantdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/certification-realm
            jwk-set-uri: http://localhost:8080/realms/certification-realm/protocol/openid-connect/certs

server:
  port: 8081

springdoc:
  api-docs:
    path: COMMERCANT-SERVICE-SERVER/swagger-ui/index.html
  swagger-ui:
    path: /swagger-ui.html
